name: Create jb
 
on:
  push:
    branches: ["main"]
 
jobs:
  create-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main
 
      - name: Create and Run Job
        run: |
          export DATABRICKS_HOST="https://adb-1670050298591902.2.azuredatabricks.net"
          export DATABRICKS_TOKEN="dapi43bfe94722db1bd799eabea16d019378-3"
          # Create a job that runs the imported notebook
          JOB_JSON=$(databricks jobs create --json '{
            "name": "pipeline-validation-notebook-job",
            "tasks": [
              {
                "task_key": "run_notebook",
                "notebook_task": {
                  "notebook_path": "/Workspace/Users/deni.lakamsani@snp.com/src_notebook/src_folder/Job_Creation"
                },
                "existing_cluster_id": "1124-095229-bom9cuxu"
              }
            ]
          }')

          JOB_ID=$(echo "$JOB_JSON" | jq -r '.job_id')

          # Run the job
          databricks jobs run-now --job-id "$JOB_ID"
